// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Q2_Part1.Models;

#nullable disable

namespace Q2_Part1.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20240102101859_MyBook")]
    partial class MyBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Q2_Part1.Models.Books", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("BookAuthor")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BookTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Isbn")
                        .HasColumnType("int")
                        .HasColumnName("ISBN");

                    b.Property<string>("PublicationYear")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Publication_Year");

                    b.HasKey("BookId")
                        .HasName("PK__Book_Inf__3DE0C2078D7FE96E");

                    b.ToTable("Book_Info", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
